import uuid
from decimal import Decimal
from sqlalchemy import String, Integer, Numeric, Boolean, UniqueConstraint, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column
from app.db import Base


class PLLine(Base):
    """
    One persisted P&L line per scenario × month × line_code.
    Regenerated by recalculate_scenario() / the P&L engine.
    See app/engine/pl_engine.py for line_code / section vocab.
    """
    __tablename__ = "pl_lines"
    __table_args__ = (
        UniqueConstraint("scenario_id", "month", "line_code", name="uq_pl_line"),
    )

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    scenario_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("scenarios.id", ondelete="CASCADE"), index=True
    )
    month: Mapped[int] = mapped_column(Integer)
    year: Mapped[int] = mapped_column(Integer, default=2026)
    line_code: Mapped[str] = mapped_column(String(60))    # 'REV_ROOMS', 'TOTAL_OPERATING_EXPENSES', ...
    line_name: Mapped[str] = mapped_column(String(120))
    section: Mapped[str] = mapped_column(String(60))      # 'REVENUES', 'OWNER / NON-OP EXPENSES', ...
    dept_code: Mapped[str] = mapped_column(String(20), default="")  # group key or ''
    amount_usd: Mapped[Decimal] = mapped_column(Numeric(16, 4), default=Decimal("0"))
    is_calculated: Mapped[bool] = mapped_column(Boolean, default=True)

    def __repr__(self) -> str:
        return f"<PLLine {self.line_code} m{self.month} ${self.amount_usd}>"
