# -*- coding: utf-8 -*-
"""El rótulo de cada fila del Cash Flow Directo -> su clave de traducción.

⚠️ **El motor no traduce: nombra.** Emite `label` (el texto que siempre emitió,
como respaldo) y `label_key`. La pantalla muestra el catálogo si hay clave, y el
`label` si no. Misma regla que `ayuda_cashflow.py` y que el `line_code` del P&L.

⚠️ **Los rótulos DINÁMICOS no están acá a propósito.** Las filas por
departamento se rotulan con el nombre que viene de la base —`f"  {l}"`— y eso es
DATO, no interfaz: no se traduce. Al no encontrarse en este mapa, salen sin
`label_key` y la pantalla usa el nombre tal cual llega.
"""

ETIQUETAS: dict[str, str] = {
    "(+) Cargas sociales patronales": "cargas_sociales_patronales",
    "(+) Crédito generado en el mes": "credito_generado_en_el_mes",
    "(+) Depósitos recibidos por estadías futuras": "depositos_recibidos_por_estadias_futuras",
    "(+) Otros beneficios": "otros_beneficios",
    "(informativo) Financiamiento requerido": "informativo_financiamiento_requerido",
    "(se le paga a los empleados el mes siguiente)": "se_le_paga_a_los_empleados_el_mes_siguiente",
    "(se ven dentro de «Pago a proveedores y planilla»)": "se_ven_dentro_de_pago_a_proveedores_y_planilla",
    "(±) Movimiento de cuentas por cobrar": "movimiento_de_cuentas_por_cobrar",
    "(±) Movimiento de cuentas por pagar": "movimiento_de_cuentas_por_pagar",
    "(−) Ajuste al movimiento real": "ajuste_al_movimiento_real",
    "(−) Crédito aplicado contra el impuesto": "credito_aplicado_contra_el_impuesto",
    "(−) Depósitos aplicados a la estadía del mes": "depositos_aplicados_a_la_estadia_del_mes",
    "(−) Retención de renta al salario (por tramos)": "retencion_de_renta_al_salario_por_tramos",
    "= COBRO OPERATIVO": "cobro_operativo",
    "= POSICIÓN DEL MES (débito − crédito)": "posicion_del_mes_debito_credito",
    "= SALARIO BRUTO": "salario_bruto",
    "= SALDO A FAVOR FINAL": "saldo_a_favor_final",
    "A Hacienda (retención de renta al salario)": "a_hacienda_retencion_de_renta_al_salario",
    "A declarar este mes (nunca negativo)": "a_declarar_este_mes_nunca_negativo",
    "A la CCSS (cotización obrera retenida)": "a_la_ccss_cotizacion_obrera_retenida",
    "A. COSTO DE PLANILLA POR DEPARTAMENTO": "a_costo_de_planilla_por_departamento",
    "A. COSTO DEVENGADO DEL MES": "a_costo_devengado_del_mes",
    "A. GASTOS DE PROPIEDAD DEVENGADOS (below-GOP)": "a_gastos_de_propiedad_devengados_below_gop",
    "A. IVA DEL MES (devengado)": "a_iva_del_mes_devengado",
    "A. VENTA DEVENGADA (sin IVA)": "a_venta_devengada_sin_iva",
    "Aguinaldo (provisión)": "aguinaldo_provision",
    "Ajuste al movimiento real de la otra pantalla": "ajuste_al_movimiento_real_de_la_otra_pantalla",
    "Al empleado (neto en la mano)": "al_empleado_neto_en_la_mano",
    "Alquiler": "alquiler",
    "B. AUXILIAR DEL SALDO A FAVOR": "b_auxiliar_del_saldo_a_favor",
    "B. CÓMO SE PAGAN": "b_como_se_pagan",
    "B. DEL BRUTO A LA NETA (lo que recibe el empleado)": "b_del_bruto_a_la_neta_lo_que_recibe_el_empleado",
    "B. DEL GASTO AL PAGO": "b_del_gasto_al_pago",
    "B. IVA COBRADO": "b_iva_cobrado",
    "B2. A DÓNDE VA EL SALARIO BRUTO": "b2_a_donde_va_el_salario_bruto",
    "C. CARGAS SOCIALES PATRONALES (encima del bruto)": "c_cargas_sociales_patronales_encima_del_bruto",
    "C. CÓMO SE REPARTE EL PAGO": "c_como_se_reparte_el_pago",
    "C. DE LA VENTA AL COBRO": "c_de_la_venta_al_cobro",
    "C. INVERSIÓN": "c_inversion",
    "C. LIQUIDACIÓN": "c_liquidacion",
    "CCSS patronal": "ccss_patronal",
    "Cafetería": "cafeteria",
    "CapEx del presupuesto (del P&L)": "capex_del_presupuesto_del_p_l",
    "Cesantía (provisión)": "cesantia_provision",
    "Cobro a clientes (con IVA, neto de retenciones de tarjeta)": "cobro_a_clientes_con_iva_neto_de_retenciones_de_tarj",
    "D. LO QUE BAJA AL FLUJO": "d_lo_que_baja_al_flujo",
    "D. OTROS BENEFICIOS": "d_otros_beneficios",
    "D. OTROS COBROS": "d_otros_cobros",
    "E. MEMO — el IVA que viaja dentro de otras líneas": "e_memo_el_iva_que_viaja_dentro_de_otras_lineas",
    "E. RESUMEN": "e_resumen",
    "Efecto neto del IVA en caja": "efecto_neto_del_iva_en_caja",
    "El IVA cobrado va dentro de «Cobro a clientes»": "el_iva_cobrado_va_dentro_de_cobro_a_clientes",
    "El IVA pagado va dentro de «Pago a proveedores»": "el_iva_pagado_va_dentro_de_pago_a_proveedores",
    "Entran al mismo calendario de proveedores": "entran_al_mismo_calendario_de_proveedores",
    "FLUJO NETO TOTAL": "flujo_neto_total",
    "FLUJO OPERATIVO": "flujo_operativo",
    "Gastos de propiedad (ver su tab)": "gastos_de_propiedad_ver_su_tab",
    "Honorarios de administración": "honorarios_de_administracion",
    "INS — riesgos del trabajo": "ins_riesgos_del_trabajo",
    "IVA cobrado a clientes": "iva_cobrado_a_clientes",
    "IVA cobrado a clientes (+)": "iva_cobrado_a_clientes_2",
    "IVA pagado a proveedores (−)": "iva_pagado_a_proveedores",
    "Impuesto de renta — liquidación (sale una vez)": "impuesto_de_renta_liquidacion_sale_una_vez",
    "Incapacidades": "incapacidades",
    "La deducción obrera se retiene y se remite: la caja paga el costo total": "la_deduccion_obrera_se_retiene_y_se_remite_la_caja_p",
    "Las dos son 2.5%: el adquirente las descuenta al liquidar": "las_dos_son_2_5_el_adquirente_las_descuenta_al_liqui",
    "Otros": "otros",
    "Otros gastos": "otros_gastos",
    "Otros movimientos de caja": "otros_movimientos_de_caja",
    "Sin clasificar (está en el total, sin línea propia)": "below_gop_sin_clasificar",
    "Pago a la CCSS (cuota patronal + obrera)": "pago_a_la_ccss_cuota_patronal_obrera",
    "Pago a proveedores (con IVA)": "pago_a_proveedores_con_iva",
    "Pago de aguinaldo (se provisiona y sale en su mes)": "pago_de_aguinaldo_se_provisiona_y_sale_en_su_mes",
    "Pago de planilla neta (a empleados)": "pago_de_planilla_neta_a_empleados",
    "Pago total del mes (sin IVA)": "pago_total_del_mes_sin_iva",
    "Planilla": "planilla",
    "Proveedores": "proveedores",
    "Remesa a Hacienda de lo declarado el mes anterior": "remesa_a_hacienda_de_lo_declarado_el_mes_anterior",
    "Remesa de IVA a Hacienda": "remesa_de_iva_a_hacienda",
    "Remesa de IVA a Hacienda (ver tab Impuestos)": "remesa_de_iva_a_hacienda_ver_tab_impuestos",
    "Retención de IVA de tarjeta (va neta del cobro)": "retencion_de_iva_de_tarjeta_va_neta_del_cobro",
    "Retención de IVA de tarjeta (−)": "retencion_de_iva_de_tarjeta",
    "Retención de RENTA de tarjeta (va neta del cobro)": "retencion_de_renta_de_tarjeta_va_neta_del_cobro",
    "SALDO FINAL DE CAJA": "saldo_final_de_caja",
    "Salario bruto": "salario_bruto_2",
    "Salario bruto (base imponible)": "salario_bruto_base_imponible",
    "Saldo Inicial de Caja": "saldo_inicial_de_caja",
    "Saldo inicial (viene del mes anterior)": "saldo_inicial_viene_del_mes_anterior",
    "Seguros de la propiedad": "seguros_de_la_propiedad",
    "Servicio 10% A&B cobrado al huésped": "servicio_10_a_b_cobrado_al_huesped",
    "Servicio 10% A&B pagado a empleados": "servicio_10_a_b_pagado_a_empleados",
    "TOTAL BENEFICIOS": "total_beneficios",
    "TOTAL CARGAS SOCIALES": "total_cargas_sociales",
    "TOTAL COSTO DE PLANILLA": "total_costo_de_planilla",
    "TOTAL COSTO DEVENGADO": "total_costo_devengado",
    "TOTAL ENTRADAS": "total_entradas",
    "TOTAL GASTOS DE PROPIEDAD": "total_gastos_de_propiedad",
    "TOTAL IVA COBRADO": "total_iva_cobrado",
    "TOTAL SALIDAS OPERATIVAS": "total_salidas_operativas",
    "TOTAL VENTA DEVENGADA": "total_venta_devengada",
    "Total deducciones al empleado": "total_deducciones_al_empleado",
    "Transporte": "transporte",
    "Vacaciones (provisión)": "vacaciones_provision",
    "Venta devengada del mes": "venta_devengada_del_mes",
    "Vivienda": "vivienda",
    "▶ COSTO TOTAL DE PLANILLA (al P&L)": "costo_total_de_planilla_al_p_l",
    "▶ ENTRADAS DE EFECTIVO": "entradas_de_efectivo",
    "▶ INVERSIÓN": "inversion",
    "▶ PLANILLA NETA A PAGAR AL EMPLEADO": "planilla_neta_a_pagar_al_empleado",
    "▶ POSICIÓN DE CAJA": "posicion_de_caja",
    "▶ REMESA DE IVA (una línea en el Resumen)": "remesa_de_iva_una_linea_en_el_resumen",
    "▶ SALIDAS DE EFECTIVO": "salidas_de_efectivo",
    "▶ TOTAL ENTRADAS DE CAJA": "total_entradas_de_caja",
    "▶ TOTAL PAGADO (sin IVA)": "total_pagado_sin_iva",
    "▶ TOTAL PROPIEDAD + INVERSIÓN": "total_propiedad_inversion",
    "Inversión / CapEx adicional": "inversion_capex_adicional",
    "Reserva de reposición (FF&E)": "reserva_de_reposicion_ff_e",
    "Otra inversión de capital": "otra_inversion_de_capital",
    "Préstamos recibidos (+)": "prestamos_recibidos",
    "Servicio de deuda (amortización)": "servicio_de_deuda_amortizacion",
    "Intereses": "intereses",
    "Distribuciones / retiros": "distribuciones_retiros",
    "Otras entradas manuales (+)": "otras_entradas_manuales",
    "Otras salidas manuales": "otras_salidas_manuales",
    "▶ INVERSIÓN DE CAPITAL ADICIONAL (manual)": "inversion_de_capital_adicional_manual",
    "▶ PRÉSTAMOS E INTERESES (manual)": "prestamos_e_intereses_manual",
    "▶ AJUSTES MANUALES": "ajustes_manuales",
    "Subtotal Capital": "subtotal_capital",
    "Subtotal Financiamiento": "subtotal_financiamiento",
    "Subtotal Ajustes": "subtotal_ajustes",
}
